BEGIN;

ALTER TABLE public.consignments
  ADD COLUMN IF NOT EXISTS freight_deduction NUMERIC(14, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS additional_freight NUMERIC(14, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS loading_deduction NUMERIC(14, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS additional_loading NUMERIC(14, 2) NOT NULL DEFAULT 0;

COMMIT;
