BEGIN;

ALTER TABLE public.shipments
  ADD COLUMN IF NOT EXISTS sub_supply_desc TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS actual_from_state_code TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS actual_to_state_code TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS transaction_type TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS total_value NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cgst_value NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sgst_value NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS igst_value NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cess_value NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cess_non_advol_value NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS other_value NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS supplier_address_line_1 TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS supplier_address_line_2 TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS recipient_address_line_1 TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS recipient_address_line_2 TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS dispatch_from_address_line_1 TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS dispatch_from_address_line_2 TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ship_to_address_line_1 TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ship_to_address_line_2 TEXT NOT NULL DEFAULT '';

ALTER TABLE public.shipment_items
  ADD COLUMN IF NOT EXISTS product_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cgst_rate NUMERIC(6,3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sgst_rate NUMERIC(6,3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS igst_rate NUMERIC(6,3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cess_rate NUMERIC(6,3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cess_nonadvol NUMERIC(14,2) NOT NULL DEFAULT 0;

COMMIT;
