-- GPS tracking app credentials and trip recording sessions.
-- Run this migration in the same Supabase project used by Garuda ERP and Colota.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE public.drivers
  ADD COLUMN IF NOT EXISTS tracking_app_id text,
  ADD COLUMN IF NOT EXISTS tracking_app_password text,
  ADD COLUMN IF NOT EXISTS tracking_app_password_hash text;

CREATE UNIQUE INDEX IF NOT EXISTS drivers_tracking_app_id_idx
  ON public.drivers (tracking_app_id)
  WHERE tracking_app_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.sync_tracking_app_password_hash()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
  IF TG_OP = 'INSERT'
     OR NEW.tracking_app_password IS DISTINCT FROM OLD.tracking_app_password
     OR NEW.tracking_app_password_hash IS NULL THEN
    IF NULLIF(NEW.tracking_app_password, '') IS NULL THEN
      NEW.tracking_app_password_hash := NULL;
    ELSE
      NEW.tracking_app_password_hash := crypt(NEW.tracking_app_password, gen_salt('bf', 12));
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS drivers_tracking_app_password_hash ON public.drivers;
CREATE TRIGGER drivers_tracking_app_password_hash
  BEFORE INSERT OR UPDATE OF tracking_app_password, tracking_app_password_hash
  ON public.drivers
  FOR EACH ROW EXECUTE FUNCTION public.sync_tracking_app_password_hash();

CREATE TABLE IF NOT EXISTS public.driver_gps_tracking_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  trip_id uuid NOT NULL REFERENCES public.trips(id) ON DELETE CASCADE,
  driver_id uuid NOT NULL REFERENCES public.drivers(id) ON DELETE RESTRICT,
  started_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS driver_gps_tracking_one_active_trip_idx
  ON public.driver_gps_tracking_sessions (trip_id)
  WHERE ended_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS driver_gps_tracking_one_active_driver_idx
  ON public.driver_gps_tracking_sessions (driver_id)
  WHERE ended_at IS NULL;
CREATE INDEX IF NOT EXISTS driver_gps_tracking_driver_idx
  ON public.driver_gps_tracking_sessions (driver_id, started_at DESC);

CREATE TABLE IF NOT EXISTS public.driver_gps_locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id uuid NOT NULL REFERENCES public.driver_gps_tracking_sessions(id) ON DELETE CASCADE,
  trip_id uuid NOT NULL REFERENCES public.trips(id) ON DELETE CASCADE,
  driver_id uuid NOT NULL REFERENCES public.drivers(id) ON DELETE RESTRICT,
  latitude double precision NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude double precision NOT NULL CHECK (longitude BETWEEN -180 AND 180),
  accuracy_m double precision CHECK (accuracy_m IS NULL OR accuracy_m >= 0),
  recorded_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS driver_gps_locations_trip_time_idx
  ON public.driver_gps_locations (trip_id, recorded_at ASC);

ALTER TABLE public.driver_gps_tracking_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.driver_gps_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.driver_gps_tracking_sessions FORCE ROW LEVEL SECURITY;
ALTER TABLE public.driver_gps_locations FORCE ROW LEVEL SECURITY;
REVOKE ALL ON public.driver_gps_tracking_sessions, public.driver_gps_locations FROM anon, authenticated;
GRANT ALL ON public.driver_gps_tracking_sessions, public.driver_gps_locations TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.driver_gps_locations_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.start_driver_gps_tracking(p_trip_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, extensions AS $$
DECLARE v_trip record; v_session record;
BEGIN
  SELECT id, driver_id, trip_code INTO v_trip FROM public.trips
  WHERE id = p_trip_id AND ownership = 'own' AND COALESCE(closed, false) = false AND driver_id IS NOT NULL;
  IF NOT FOUND THEN RAISE EXCEPTION 'Only an open own-vehicle trip with an assigned driver can start tracking'; END IF;
  SELECT * INTO v_session FROM public.driver_gps_tracking_sessions
  WHERE trip_id = p_trip_id AND ended_at IS NULL FOR UPDATE;
  IF FOUND THEN RETURN jsonb_build_object('ok', true, 'active', true, 'session_id', v_session.id, 'started_at', v_session.started_at); END IF;
  INSERT INTO public.driver_gps_tracking_sessions (trip_id, driver_id)
  VALUES (v_trip.id, v_trip.driver_id) RETURNING * INTO v_session;
  RETURN jsonb_build_object('ok', true, 'active', true, 'session_id', v_session.id, 'started_at', v_session.started_at);
END;
$$;

CREATE OR REPLACE FUNCTION public.stop_driver_gps_tracking(p_trip_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, extensions AS $$
DECLARE v_session record;
BEGIN
  UPDATE public.driver_gps_tracking_sessions SET ended_at = now()
  WHERE trip_id = p_trip_id AND ended_at IS NULL RETURNING * INTO v_session;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok', true, 'active', false); END IF;
  RETURN jsonb_build_object('ok', true, 'active', false, 'ended_at', v_session.ended_at);
END;
$$;

CREATE OR REPLACE FUNCTION public.get_driver_gps_tracking_status(p_trip_id uuid)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public, extensions AS $$
  SELECT COALESCE((SELECT jsonb_build_object('active', true, 'session_id', id, 'started_at', started_at)
    FROM public.driver_gps_tracking_sessions WHERE trip_id = p_trip_id AND ended_at IS NULL LIMIT 1),
    jsonb_build_object('active', false));
$$;

REVOKE ALL ON FUNCTION public.start_driver_gps_tracking(uuid), public.stop_driver_gps_tracking(uuid), public.get_driver_gps_tracking_status(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.start_driver_gps_tracking(uuid), public.stop_driver_gps_tracking(uuid), public.get_driver_gps_tracking_status(uuid) TO anon, authenticated;

-- Closed trips retain the GPS history; only the active recording session is stopped.
CREATE OR REPLACE FUNCTION public.stop_gps_tracking_when_trip_closes()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.closed IS TRUE AND COALESCE(OLD.closed, false) IS FALSE THEN
    UPDATE public.driver_gps_tracking_sessions SET ended_at = COALESCE(ended_at, now()) WHERE trip_id = NEW.id AND ended_at IS NULL;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trips_stop_gps_tracking_on_close ON public.trips;
CREATE TRIGGER trips_stop_gps_tracking_on_close AFTER UPDATE OF closed ON public.trips FOR EACH ROW EXECUTE FUNCTION public.stop_gps_tracking_when_trip_closes();

-- Verification
SELECT to_regclass('public.driver_gps_tracking_sessions') AS tracking_sessions,
       to_regclass('public.driver_gps_locations') AS gps_locations,
       to_regprocedure('public.start_driver_gps_tracking(uuid)') AS start_function,
       to_regprocedure('public.stop_driver_gps_tracking(uuid)') AS stop_function;
